### ISSUE TITLE
Error running Docker-Image v0.1.4

### ISSUE THREAD

**Issue by christianknell** [mrueg/netcupscp-exporter#5]
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7f0835]
goroutine 27 [running]:
github.com/mrueg/netcupscp-exporter/pkg/metrics.(*scpCollector).Collect(0xc000204d20, 0xc000064f60?)
	/go/src/github.com/mrueg/netcupscp-exporter/pkg/metrics/metrics.go:198 +0xed5
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:453 +0xfb
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:545 +0xbab
```

**Comment by christianknell** [comment]
I experience this bug when one of my two instances is shutdown. After turning the second one on again, the container keeps on running.

**Comment by mrueg** [comment]
And this is something you experience only with 0.1.4? Not 0.1.3?

**Comment by mrueg** [comment]
Please test with v0.1.5

**Comment by christianknell** [comment]
works with v0.1.5
